apiVersion: apps/v1
kind: Deployment
metadata:
  name: netli
  labels:
    app: netli
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: netli
    spec:
      containers:
      - name: netli
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 80
